--@Autor: Berdejo Arvizu Oscar || Olmos Cruz Edwin
--@Fecha creación: 25/10/2018
--@Descripción: Creacion De vistas
--Usuario Admin: baoc_proy_admin
--Usuario Invitado: baoc_proy_invitado

prompt creando vistas
prompt conectando usuario baoc_proy_admin
connect baoc_proy_admin

CREATE OR REPLACE VIEW V_ESTUDIANTE(
    NOMBRE,AP_PATERNO,AP_MATERNO, NUM_INSCRIPCION)
    AS SELECT NOMBRE, AP_PATERNO,AP_MATERNO, NUM_INSCRIPCION
    FROM ESTUDIANTE E, INSCRIPCION I
    WHERE E.ESTUDIANTE_ID=I.ESTUDIANTE_ID;

CREATE OR REPLACE VIEW V_PROFESOR(
    NOMBRE,AP_PATERNO,AP_MATERNO, TIPO_PROFESOR)
    AS SELECT NOMBRE,AP_PATERNO, AP_MATERNO, TIPO_PROFESOR
    FROM PROFESOR;

CREATE OR REPLACE VIEW V_ASIGNATURA(
    CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS)
    AS SELECT CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS
    FROM ASIGNATURA A;

CREATE OR REPLACE VIEW V_ESTATUS_TESIS(
    TESIS_ID, NOMBRE, OBJETIVO, CLAVE)
    AS SELECT TESIS_ID, NOMBRE, OBJETIVO, CLAVE
    FROM TESIS T, ESTATUS ES
    WHERE  T.ESTATUS_ID = ES.ESTATUS_ID;