--Insert Puesto
INSERT INTO PUESTO(PUESTO_ID, NOMBRE, DESCRIPCION, SUELDO)VALUES(1, 'COORDINADOR DE CARRERA', 'VERIFICA CALIDAD EN LA CARRERA', 40000);
INSERT INTO PUESTO(PUESTO_ID, NOMBRE, DESCRIPCION, SUELDO)VALUES(2, 'INVESTIGADOR', 'MANTIENE EL RENOMBRE DE LA CARRERA', 35000);
--Insert Estatus
INSERT INTO ESTATUS(ESTATUS_ID, CLAVE, DESCRIPCION) VALUES (1, 'EN PROCESO', 'SE ESTA VALIDANDO LA TESIS');
INSERT INTO ESTATUS(ESTATUS_ID, CLAVE, DESCRIPCION) VALUES (2, 'CONFIRMADA', 'YA SE TITULO :)');
INSERT INTO ESTATUS(ESTATUS_ID, CLAVE, DESCRIPCION) VALUES (3, 'CANSELADA', 'YA FUE :(');
--INSERTANDO GRADOS_ESTUDIOS
INSERT INTO GRADO_ESTUDIOS(GRADOS_ESTUDIOS_ID,DESCRIPCION,FECHA)VALUES(1,'MAESTRIA EN INTELIGENCIA ARTIFICIAL',TO_DATE('11/09/1992','DD/MM/YYYY'));
INSERT INTO GRADO_ESTUDIOS(GRADOS_ESTUDIOS_ID,DESCRIPCION,FECHA)VALUES(2,'DOCTORADO EN SISTEMAS AUTOMATAS',TO_DATE('09/29/2002','DD/MM/YYYY'));
INSERT INTO GRADO_ESTUDIOS(GRADOS_ESTUDIOS_ID,DESCRIPCION,FECHA)VALUES(3,'POSGRADO EN POTENCIA ELECTRICA',TO_DATE('19/09/2011','DD/MM/YYYY'));
--INSERTANDO PROFESORES
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,NUM_CEDULA,TIPO_PROFESOR)VALUES(PROFESOR_SEQ.NEXTVAL,'LUIS','FERNANDEZ','MENDEZ','FEML870411','1239871','C');
INSERT INTO PROFESOR_CARRERA(PROFESOR_ID, GRADO_MAX_ES_ID, FECHA)VALUES(PROFESOR_SEQ.CURRVAL,2,to_date(sysdate,'DD/MM/YYYY'));
INSERT INTO GRADO_ESTUDIOS_HISTORICO(GRADO_ESTUDIOS_HISTORICO_ID,FECHA,PROFESOR_ID,GRADOS_ESTUDIOS_ID)VALUES(HIS_GE_SEQ.NEXTVAL,TO_DATE('11/09/1992','DD/MM/YYYY'),PROFESOR_SEQ.CURRVAL,1);
INSERT INTO GRADO_ESTUDIOS_HISTORICO(GRADO_ESTUDIOS_HISTORICO_ID,FECHA,PROFESOR_ID,GRADOS_ESTUDIOS_ID)VALUES(HIS_GE_SEQ.NEXTVAL,TO_DATE('09/29/2002','DD/MM/YYYY'),PROFESOR_SEQ.CURRVAL,2);

INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,NUM_CEDULA,TIPO_PROFESOR)VALUES(PROFESOR_SEQ.NEXTVAL,'OSCAR','HERNANDEZ','TABOADA','HETO870411','1232345','A');
INSERT INTO PROFESOR_ADMINISTRADOR(PROFESOR_ID, PUESTO_ID)VALUES(PROFESOR_SEQ.CURRVAL,1);

INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,NUM_CEDULA,TIPO_PROFESOR)VALUES(PROFESOR_SEQ.NEXTVAL,'FERNANDA','NAVARRO','JIMENEZ','NAJF832411','13332345','S');
INSERT INTO PROFESOR_ASIGNATURA(PROFESOR,ID,NUM_CONTRATO,FECHA_INICIO,FECHA_FIN)VALUES(PROFESOR_SEQ.NEXTVAL,1111,TO_DATE('11/04/1996','DD/MM/YYYY'),TO_DATE('11/04/2020','DD/MM/YYYY'));

---ESTUDIANTE--
---FALTA ASIGANR TESIS__ID
INSERT INTO ESTUDIANTE(ESTUDIANTE_ID, NUM_CUENTA, NOMBRE, AP_PATERNO, AP_MATERNO, CARRERA_ID, PLAN_ESTUDIOS_ID, TESIS_ID) VALUES
(1,4150, 'EDWIN', 'OLMOS', 'CRUZ', 1,10,1);
INSERT INTO ESTUDIANTE(ESTUDIANTE_ID, NUM_CUENTA, NOMBRE, AP_PATERNO, AP_MATERNO, CARRERA_ID, PLAN_ESTUDIOS_ID, TESIS_ID) VALUES
(2,4151,'JUAN', 'SANDATE', 'SANTOS',2,11,1);
INSERT INTO ESTUDIANTE(ESTUDIANTE_ID, NUM_CUENTA, NOMBRE, AP_PATERNO, AP_MATERNO, CARRERA_ID, PLAN_ESTUDIOS_ID, TESIS_ID) VALUES
(3,4153, 'OSCAR', 'BERDEJO', 'ARVIZU'1,12,2);
INSERT INTO ESTUDIANTE(ESTUDIANTE_ID, NUM_CUENTA, NOMBRE, AP_PATERNO, AP_MATERNO, CARRERA_ID, PLAN_ESTUDIOS_ID, TESIS_ID) VALUES
(4,4154, 'JORGE', 'CAMPOS', 'HERNANZDEZ',3,13,null);
INSERT INTO ESTUDIANTE(ESTUDIANTE_ID, NUM_CUENTA, NOMBRE, AP_PATERNO, AP_MATERNO, CARRERA_ID, PLAN_ESTUDIOS_ID, TESIS_ID) VALUES
(5,4155,'HECTOR', 'ANICETO', 'LOPEZ', 2,10,null);

---INSCRIPCION---

INSERT INTO INSCRIPCION(INSCRIPCION_ID, NUM_INSCRIPCION, ESTUDIANTE_ID) VALUES (INSCRIPCION_SEQ.NEXTVAL,1000,1);
INSERT INTO INSCRIPCION(INSCRIPCION_ID, NUM_INSCRIPCION, ESTUDIANTE_ID) VALUES (INSCRIPCION_SEQ.NEXTVAL,1001,2);
INSERT INTO INSCRIPCION(INSCRIPCION_ID, NUM_INSCRIPCION, ESTUDIANTE_ID) VALUES (INSCRIPCION_SEQ.NEXTVAL,2000,3);
INSERT INTO INSCRIPCION(INSCRIPCION_ID, NUM_INSCRIPCION, ESTUDIANTE_ID) VALUES (INSCRIPCION_SEQ.NEXTVAL,3000,4);
INSERT INTO INSCRIPCION(INSCRIPCION_ID, NUM_INSCRIPCION, ESTUDIANTE_ID) VALUES (INSCRIPCION_SEQ.NEXTVAL,2055,5);

-----CARRERA----

INSERT INTO  CARRERA(CARRERA_ID,CLAVE, NOMBRE, DESCRPCION) VALUES (1, 110, 'ING.COMPUTACION', 'SOPORTE TECNICO AL PROCESAMIENTO DE DATOS');
INSERT INTO  CARRERA(CARRERA_ID,CLAVE, NOMBRE, DESCRPCION) VALUES (2, 111, 'ING.ELECTRICA-ELECTRONICA', 'SOPORTE TECNICO A SISTEMAS ELECTRICOS');
INSERT INTO  CARRERA(CARRERA_ID,CLAVE, NOMBRE, DESCRPCION) VALUES (3, 112, 'ING.TELECOMUNICACIONES', 'SOPORTE TECNICO AL CONTROL DIGITAL DE PROCESOS AUTOMATICOS');

-----INSERCIONES PLAN DE ESTUDIOS----------
INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,PLAN_SUSTITUTO_ID, CLAVE,NOMBRE,FECHA_APROBACION,FECHA_TERMINO) VALUES 
(10,NULL,101,'INGENIERA EN COMPUTACION',TO_DATE('15/02/2010','DD/MM/YYYY'),TO_DATE('15/02/2016','DD/MM/YYYY');
INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,PLAN_SUSTITUTO_ID, CLAVE,NOMBRE,FECHA_APROBACION,FECHA_TERMINO) VALUES 
(11,10,102,'INGENIERA EN COMPUTACION',TO_DATE('16/02/2016','DD/MM/YYYY'),TO_DATE('19/02/2018','DD/MM/YYYY');
INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,PLAN_SUSTITUTO_ID, CLAVE,NOMBRE,FECHA_APROBACION,FECHA_TERMINO) VALUES 
(12,NULL,102,'INGENIERA EN ELECTRICA-ELECTRONICA',TO_DATE('10/02/2016','DD/MM/YYYY'),TO_DATE('25/02/2026','DD/MM/YYYY'));
INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,PLAN_SUSTITUTO_ID, CLAVE,NOMBRE,FECHA_APROBACION,FECHA_TERMINO) VALUES
(13,NULL,103,'TELECOMUNICACIONES',TO_DATE('25/02/2010','DD/MM/YYYY',TO_DATE('25/02/2016','DD/MM/YYYY'));
	------ASIGNATURA-----


INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (1, NULL, 1100, 'ALGEBRA', 1, 09,10);
INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (2, 1, 0062, 'ALGEBRA LINEAL ', 2, 09,10);
INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (3, NULL, 1108, 'CALCULO DIFERENCIAL', 1, 09,11);
INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (4, 3, 1100, 'CALCULO INTEGRAL', 1, 09,11);
INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (5, NULL, 1102, 'GEOMETRIA ANALITICA', 1, 09,12);
INSERT INTO ASIGNATURA (ASIGNATURA_ID, ASIGNATURA_PREVIA, CLAVE, NOMBRE, NUM_SEMESTRE, NUM_CREDITOS, PLAN_ESTUDIOS_ID) VALUES (6, 5 ,0065 , 'ESTATICA', 2, 09,12);

---ASIGNATURA_CARRERA-----

INSERT INTO CARRERA_ASIGNATURA (CARRERA_ASIGNATURA_ID, CARRERA_ID, ASIGNATURA_ID) VALUES (1,1,1);
INSERT INTO CARRERA_ASIGNATURA (CARRERA_ASIGNATURA_ID, CARRERA_ID, ASIGNATURA_ID) VALUES (2,2,3);
INSERT INTO CARRERA_ASIGNATURA (CARRERA_ASIGNATURA_ID, CARRERA_ID, ASIGNATURA_ID) VALUES (3,2,2);
INSERT INTO CARRERA_ASIGNATURA (CARRERA_ASIGNATURA_ID, CARRERA_ID, ASIGNATURA_ID) VALUES (2,3,4);
INSERT INTO CARRERA_ASIGNATURA (CARRERA_ASIGNATURA_ID, CARRERA_ID, ASIGNATURA_ID) VALUES (1,1,6);


--SEMESTRE---
INSERT INTO SEMESTRE(SEMESTRE_ID, AÑO, PERIODO) VALUES (1,2016, '-2');
INSERT INTO SEMESTRE(SEMESTRE_ID, AÑO, PERIODO) VALUES (2,2017, '-1');
INSERT INTO SEMESTRE(SEMESTRE_ID, AÑO, PERIODO) VALUES (3,2018, '-2');
INSERT INTO SEMESTRE(SEMESTRE_ID, AÑO, PERIODO) VALUES (4,2019, '-1');

---CURSO----
---FALTA PONER ID DEL PROFESOR--

INSERT INTO CURSO(CURSO_ID, PROFESOR_ID, GRUPO, SEMESTRE_ID, ASIGNATURA_ID, CALIFICACION)VALUES(1,1,2,1,1,10);
INSERT INTO CURSO(CURSO_ID, PROFESOR_ID, GRUPO, SEMESTRE_ID, ASIGNATURA_ID, CALIFICACION)VALUES(2,2,3,2,2,5);
INSERT INTO CURSO(CURSO_ID, PROFESOR_ID, GRUPO, SEMESTRE_ID, ASIGNATURA_ID, CALIFICACION)VALUES(3,2,4,3,3,6);
INSERT INTO CURSO(CURSO_ID, PROFESOR_ID, GRUPO, SEMESTRE_ID, ASIGNATURA_ID, CALIFICACION)VALUES(4,1,5,4,4,9);
INSERT INTO CURSO(CURSO_ID, PROFESOR_ID, GRUPO, SEMESTRE_ID, ASIGNATURA_ID, CALIFICACION)VALUES(5,3,6,1,5,NULL);



--CURSO_INSCRIPCION--
INSERT INTO CURSO_INSCRIPCION(CURSO_INSCRIPCION_ID, INSCRIPCION_ID, CURSO_ID)VALUES(00,1,1);
INSERT INTO CURSO_INSCRIPCION(CURSO_INSCRIPCION_ID, INSCRIPCION_ID, CURSO_ID)VALUES(01,2,2);
INSERT INTO CURSO_INSCRIPCION(CURSO_INSCRIPCION_ID, INSCRIPCION_ID, CURSO_ID)VALUES(02,3,3);
INSERT INTO CURSO_INSCRIPCION(CURSO_INSCRIPCION_ID, INSCRIPCION_ID, CURSO_ID)VALUES(03,4,4);
INSERT INTO CURSO_INSCRIPCION(CURSO_INSCRIPCION_ID, INSCRIPCION_ID, CURSO_ID)VALUES(04,5,5);

---CLASE--
-----CLASE-----

INSERT INTO CLASE(CLASE_ID, NUM_CLASE, HORA_INICIO, HORA_FIN, NUM_SALON, DIA, CURSO_ID) VALUES (1, 10, TO_DATE('8:00',  'HH24:MI'), TO_DATE('10:00', 'HH24:MI'),20, 'LUNES',1 );
INSERT INTO CLASE(CLASE_ID, NUM_CLASE, HORA_INICIO, HORA_FIN, NUM_SALON, DIA, CURSO_ID) VALUES (2, 11, TO_DATE('10:00', 'HH24:MI'), TO_DATE('12:00', 'HH24:MI'),21, 'MARTES',2,);
INSERT INTO CLASE(CLASE_ID, NUM_CLASE, HORA_INICIO, HORA_FIN, NUM_SALON, DIA, CURSO_ID) VALUES (3, 12, TO_DATE('12:00', 'HH24:MI'), TO_DATE('14:00', 'HH24:MI'),22, 'MIERCOLES',3);
INSERT INTO CLASE(CLASE_ID, NUM_CLASE, HORA_INICIO, HORA_FIN, NUM_SALON, DIA, CURSO_ID) VALUES (4, 13, TO_DATE('14:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'),23, 'JUEVES',4);
INSERT INTO CLASE(CLASE_ID, NUM_CLASE, HORA_INICIO, HORA_FIN, NUM_SALON, DIA, CURSO_ID) VALUES (5, 14, TO_DATE('16:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'),24, 'VIERNES',5);

INSERT INTO TESIS(TESIS_ID, NOMBRE, FECHA, OBJETIVO, ESTATUS_ID, DIRECTOR_ID) 
	VALUES(1,'ROBOTS AUTOMATAS', TO_DATE('11/10/2008','DD/MM/YYYY'),'CREAR ROBOTS',2,1);
INSERT INTO TESIS(TESIS_ID, NOMBRE, FECHA, OBJETIVO, ESTATUS_ID, DIRECTOR_ID) 
	VALUES(2,'POTENCIA ELECTRICA', TO_DATE('11/10/2018','DD/MM/YYYY'),'MEJOR CONDUCCION DE LUZ',1,1);

INSERT INTO TESIS_PROFESOR_ASIGNATURA(TESIS_PROFESOR_ASIGNATURA_ID, TESIS_ID, PROFESOR_SINODAL_ID)
	VALUES(1,1,3);