--INSERT INTO GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID, DESCRIPCION) 
--VALUES (3, 'POSGRADO EN POTENCIA ELECTRICA');

--UPDATE PROFESOR_CARRERA
--SET GRADO_MAX_ES_ID = 3
--WHERE PROFESOR_ID = 1;

--SELECT * FROM GRADO_ESTUDIOS_HISTORICO;

UPDATE CURSO 
SET CALIFICACION = 9
WHERE CURSO_ID = 1;

SELECT * FROM bitacoraCalif;